---
- name: Build Docker container
  hosts: localhost
  gather_facts: false
  connection: community.docker.docker_api
  vars:
    container_name: '{{ metatrader_container_name | default("metatrader-worker") }}'
    docker_image: '{{ metatrader_base_image | default("ubuntu:latest") }}'
  tasks:
    - name: Pull image  # noqa: syntax-check[unknown-module]
      community.docker.docker_image:
        name: '{{ docker_image }}'
        source: pull
    - name: Run container
      community.docker.docker_container:
        command: sleep infinity
        container_default_behavior: compatibility
        detach: true
        hostname: '{{ container_name }}'
        image: '{{ docker_image }}'
        name: '{{ container_name }}'
        privileged: true
        state: started
    - name: Add container as host
      ansible.builtin.add_host:
        hostname: '{{ container_name }}'
- name: Configure container
  hosts: all
  gather_facts: false
  connection: community.docker.docker_api
  tasks:
    - name: Apply role
      ansible.builtin.include_role:
        name: metatrader
        tasks_from: main
    - name: Run hostname
      ansible.builtin.command: hostname
      changed_when: false
- name: Commit and push Docker image
  hosts: localhost
  gather_facts: false
  vars:
    container_name: '{{ metatrader_container_name | default("metatrader-worker") }}'
  tasks:
    - name: Commit container  # noqa: syntax-check[unknown-module] args[module]
      community.docker.docker_image:
        container: '{{ container_name }}'
        name: '{{ metatrader_docker_image }}'
        source: container
        state: present
        tag: '{{ metatrader_docker_tag }}'
    - name: Push image  # noqa: syntax-check[unknown-module]
      community.docker.docker_image:
        name: '{{ metatrader_docker_image }}'
        push: true
        source: local
        tag: '{{ metatrader_docker_tag }}'
      when: metatrader_docker_push | default(false) | bool
