# A file containing a list of collections to be installed.
# Usage:
# ansible-galaxy install -r requirements.yml
---
collections:
  - name: community.docker
    version: ">=3.4.0,<4.0.0"
  - name: ansible.windows
roles:
  - name: ea31337.wine
    scm: git
    src: git+https://github.com/EA31337/ansible-role-wine.git
    version: 468fc6e4307e0e2c63ac7b06562d83e83fa9f023
  - name: ea31337.xvfb
    scm: git
    src: git+https://github.com/EA31337/ansible-role-xvfb.git
    version: 6bf9c85423fc48ae4c01158eb0ba64fe767dec4b
