# A file containing a list of collections to be installed.
# Usage:
# ansible-galaxy install -r requirements.yml
---
collections:
  - name: community.docker
    version: ">=3.4.0,<4.0.0"
  - name: ansible.windows
roles:
  - name: ea31337.wine
    scm: git
    src: git+https://github.com/EA31337/ansible-role-wine.git
    version: c849c00c90efa6c2b82f7c1d26a69a66e5973429
  - name: ea31337.xvfb
    scm: git
    src: git+https://github.com/EA31337/ansible-role-xvfb.git
    version: 6bf9c85423fc48ae4c01158eb0ba64fe767dec4b
