# A file containing a list of collections to be installed.
# Usage:
# ansible-galaxy install -r requirements.yml
---
collections:
  - name: ansible.windows
  - name: community.docker
  - name: community.general  # Required for apk, from_ini and supervisorctl modules.
    version: ">=6.0.0"
roles:
  - name: ea31337.wine
    scm: git
    src: git+https://github.com/EA31337/ansible-role-wine.git
    # This should match version in meta/main.yml
    version: v1.0.3
  - name: ea31337.xvfb
    scm: git
    src: git+https://github.com/EA31337/ansible-role-xvfb.git
    # This should match version in meta/main.yml
    version: v1.0.3
