---
- name: Detects NixOS
  ansible.builtin.command: nix-env --version
  register: nix_check
  changed_when: false
  failed_when: false
  check_mode: false
  when: ansible_facts.os_family == 'OtherLinux'
- name: Sets detected_os_family fact
  ansible.builtin.set_fact:
    detected_os_family: >-
      {{ 'NixOS' if (ansible_facts.os_family == 'OtherLinux' and nix_check.rc == 0)
      else ansible_facts.os_family }}
- name: Sets ansible_os_family to NixOS if detected
  ansible.builtin.set_fact:
    ansible_os_family: NixOS
  when: detected_os_family == 'NixOS'
- name: Collects local facts
  ansible.builtin.setup:
    filter:
      - ansible_local
  when: false
- name: Checks if platform is already exist
  ansible.builtin.stat:
    path: "{{ ansible_local['metatrader'][metatrader_version | string].path }}"
  register: stat_mt
  when: ansible_local['metatrader'] is defined
- name: Ensures platform is installed
  when:
    - ansible_local['metatrader'] is not defined
    - detected_os_family != "Windows" # gather_facts is required.
    - (stat_mt.stat is not defined) or (not stat_mt.stat.exists)
  block:
    - name: Validates variables
      ansible.builtin.assert:
        that:
          - metatrader_setup_url | length > 0
    - name: Checks if platform is already installed
      register: file_mt_installed_exists
      ansible.builtin.stat:
        path: ~/.wine/.installed-mt{{ metatrader_version }}
      when:
        - detected_os_family != "Windows"
    - name: Ensures Curl is present (standard distros)
      ansible.builtin.package:
        name: curl
        state: present
      when:
        - detected_os_family not in ["Windows", "NixOS"]
        - ansible_facts.pkg_mgr not in ["unknown", ""]
        - not file_mt_installed_exists.stat.exists
    - name: Ensures Curl is present (NixOS)
      ansible.builtin.command:
        cmd: nix-env -iA nixpkgs.curl
      register: nix_curl_install
      changed_when: "'installing' in nix_curl_install.stderr or 'copying path' in nix_curl_install.stderr"
      when:
        - detected_os_family == "NixOS"
        - not file_mt_installed_exists.stat.exists
    - name: Ensures verb installation file is present
      ansible.builtin.template:
        src: mt{{ metatrader_version }}_install.verb.j2
        dest: /tmp/mt{{ metatrader_version }}_install.verb
        mode: '0640'
      when:
        - not file_mt_installed_exists.stat.exists
    - name: Ensures MetaTrader is installed (via verb file)
      ansible.builtin.shell:
        # @todo: The winetricks command is executed directly without specifying the executable.
        # noqa command-instead-of-shell
        cmd: >
          winetricks -q /tmp/mt{{ metatrader_version }}_install.verb
          && touch ~/.wine/.installed-mt{{ metatrader_version }}
        creates: ~/.wine/.installed-mt{{ metatrader_version }}
      environment:
        DISPLAY: :0
        FONTCONFIG_FILE: '{{ ansible_facts.env.HOME }}/.config/fontconfig/fonts.conf'
        FONTCONFIG_PATH: '{{ ansible_facts.env.HOME }}/.config/fontconfig'
        WINEDEBUG: -all
        WINEDLLOVERRIDES: mscoree,mshtml=,winebrowser.exe=,dbghelp=n
        WINETRICKS_DOWNLOADER: curl
      when:
        - not file_mt_installed_exists.stat.exists
- name: Verifies
  ansible.builtin.include_tasks: verify.yml
  tags:
    - metatrader_verify
- name: Saves platform facts
  become: >-
    {{ (ansible_facts.user_id is defined and ansible_facts.user_id != 'root')
    or (detected_os_family == 'Windows') }}
  become_method: '{{ metatrader_become_method[detected_os_family] }}'
  when:
    - >-
      ansible_local['metatrader'] is not defined
      or (find_mt_path_folder)
      != ansible_local['metatrader'][metatrader_version | string].path
  block:
    - name: Sets fact
      ansible.builtin.set_fact:
        cacheable: true
        metatrader: >-
          {{ {(metatrader_version | int | string): {'path': find_mt_path_folder}} }}
      when:
        - find_mt_path_folder is defined
        - find_mt_path_folder | length > 0
        - metatrader_version is defined
    - name: Ensures that Ansible local facts directory exists (Unix)
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: directory
        mode: '0755'
      when: detected_os_family != "Windows"
    - name: Ensures that Ansible local facts directory exists (Windows)
      ansible.windows.win_file:
        # yamllint disable-line rule:line-length
        path: \\wsl.localhost\{{ wsl_distribution_name }}\home\{{ wsl_user_name }}\ansible\facts
        state: directory
      become: true
      become_method: '{{ metatrader_become_method[detected_os_family] }}'
      become_user: '{{ ansible_facts.env.USERNAME }}'
      when: detected_os_family == "Windows"
    - name: Saves role's facts (Unix)
      ansible.builtin.copy:
        content: '{{ metatrader | to_nice_json }}'
        dest: /etc/ansible/facts.d/metatrader.fact
        mode: '0644'
      when:
        - detected_os_family != "Windows"
        - metatrader is defined
    - name: Saves role's facts (Windows)
      ansible.windows.win_copy:
        content: '{{ metatrader | to_nice_json }}'
        # yamllint disable-line rule:line-length
        dest: \\wsl.localhost\{{ wsl_distribution_name }}\home\{{ wsl_user_name }}\ansible\facts\metatrader.fact
      become: true
      become_method: '{{ metatrader_become_method[detected_os_family] }}'
      become_user: '{{ ansible_facts.env.USERNAME }}'
      when:
        - detected_os_family == "Windows"
        - metatrader is defined
