---
- name: Validates variables
  assert:
    that:
      - metatrader_setup_url | length > 0
- name: Download platform
  ansible.builtin.get_url:
    dest: "{{ ansible_remote_tmp | default('/var/tmp') }}/mt5setup.exe"
    force: false
    mode: 0644
    url: "{{ metatrader_setup_url }}"
  changed_when: mt_download_res.status_code != 200
  register: mt_download_res
