---
- name: Validates variables
  assert:
    that:
      - metatrader_setup_url | length > 0
- name: Download platform
  get_url:
    dest: "{{ ansible_remote_tmp | default('/var/tmp') }}/mt5setup.exe"
    mode: 06444
    url: "{{ metatrader_setup_url }}"
