---
- name: Validates variables
  assert:
    that:
      - metatrader_setup_url | length > 0
- name: Install MetaTrader (via Winetricks)
  block:
    - name: Install verb file
      ansible.builtin.template:
        src: mt{{ metatrader_version }}_install.verb.j2
        dest: /tmp/mt{{ metatrader_version }}_install.verb
        mode: 0640
    - name: Install MetaTrader (via verb file)
      ansible.builtin.shell:
        # noqa command-instead-of-shell
        cmd: |
          export DISPLAY=:0
          export WINEDLLOVERRIDES="mscoree,mshtml="
          winetricks -q -v /tmp/mt{{ metatrader_version }}_install.verb
  when: ansible_os_family != "Windows"
