---
- name: Validates variables
  ansible.builtin.assert:
    that:
      - metatrader_setup_url | length > 0
- name: Checks if platform is already installed
  register: file_mt_installed_exists
  ansible.builtin.stat:
    path: ~/.wine/.installed-mt{{ metatrader_version }}
  when:
    - ansible_os_family != "Windows"
- name: Ensures Curl is present
  ansible.builtin.package:
    name: curl
    state: present
  when:
    - ansible_os_family != "Windows"
    - not file_mt_installed_exists.stat.exists
- name: Installs MetaTrader (via Winetricks)
  when:
    - ansible_os_family != "Windows"
    - not file_mt_installed_exists.stat.exists
  block:
    - name: Ensures verb installation file is present
      ansible.builtin.template:
        src: mt{{ metatrader_version }}_install.verb.j2
        dest: /tmp/mt{{ metatrader_version }}_install.verb
        mode: "0640"
    - name: Ensures MetaTrader is installed (via verb file)
      ansible.builtin.shell:
        # noqa command-instead-of-shell
        cmd: >
          DISPLAY=:0
          WINEDLLOVERRIDES="mscoree,mshtml=,winebrowser.exe="
          winetricks -q /tmp/mt{{ metatrader_version }}_install.verb
          && touch ~/.wine/.installed-mt{{ metatrader_version }}
        creates: ~/.wine/.installed-mt{{ metatrader_version }}
      args:
        executable: /bin/bash
    - name: Ensures verb installation file is absent
      ansible.builtin.file:
        path: /tmp/mt{{ metatrader_version }}_install.verb
        state: absent
- name: Verifies
  ansible.builtin.include_tasks: verify.yml
