---
- name: Verifies platform files exist
  tags:
    - metatrader_verify
  block:
    - name: Checks if platform's terminal exists (Unix)
      changed_when: false
      failed_when: find_mt_res.matched == 0
      ansible.builtin.find:
        paths: '{{ ansible_env.HOME }}/.wine/drive_c'
        patterns: terminal*.exe
        recurse: true
      register: find_mt_res
      when: ansible_os_family != "Windows"

    - name: Checks if platform's terminal exists (Windows)
      changed_when: false
      failed_when: find_mt_res.matched == 0
      ansible.windows.win_find:
        paths: 'C:/Program Files/MetaTrader 5'
        patterns: terminal*.exe
        recurse: true
      register: find_mt_res
      when: ansible_os_family == "Windows"

    - name: Checks if platform's editor exists (Unix)
      changed_when: false
      failed_when: find_mte_res.matched == 0
      ansible.builtin.find:
        paths: '{{ ansible_env.HOME }}/.wine/drive_c'
        patterns: "[mM]eta[eE]ditor*.exe"
        recurse: true
      register: find_mte_res
      when: ansible_os_family != "Windows"

    - name: Checks if platform's editor exists (Windows)
      changed_when: false
      failed_when: find_mte_res.matched == 0
      ansible.windows.win_find:
        paths: 'C:/Program Files/MetaTrader 5'
        patterns: "[mM]eta[eE]ditor*.exe"
        recurse: true
      register: find_mte_res
      when: ansible_os_family == "Windows"

    - name: Check WSL's default distribution name (Windows)
      changed_when: false
      failed_when: not wsl_distribution_name_result
      ansible.windows.win_powershell:
        script: >
          wsl -l -v | Select-String -Pattern '\*'
          | ForEach-Object { ($_ -split '\s+')[1] }
      register: wsl_distribution_name_result
      when: ansible_os_family == "Windows"

    - name: Store WSL's default distribution name (Windows)
      ansible.builtin.set_fact:
        wsl_distribution_name: '{{ wsl_distribution_name_result.output[0]
          | regex_replace("\u0000", "") }}'
      when: ansible_os_family == "Windows"

    - name: Check WSL's default user name (Windows)
      changed_when: false
      failed_when: not wsl_user_name_result
      ansible.windows.win_command: ubuntu -c "whoami"
      register: wsl_user_name_result
      when: ansible_os_family == "Windows"

    - name: Store WSL's default user name (Windows)
      ansible.builtin.set_fact:
        wsl_user_name: "{{ wsl_user_name_result.stdout_lines[0] }}"
      when: ansible_os_family == "Windows"
