---
- name: Verifies platform files exist
  tags:
    - metatrader_verify
  block:
    - name: Populate paths
      ansible.builtin.include_tasks: paths.yml
      args:
        apply:
          tags:
            - metatrader_paths
      tags:
        - metatrader_paths
    - name: Checks if platform's terminal exists (Unix/Cygwin)
      changed_when: false
      failed_when: find_mt_res.matched == 0
      ansible.builtin.find:
        paths: '{{ mt_runner_mt_path_host }}'
        patterns: terminal*.exe
        recurse: true
      register: find_mt_res_unix
      when: is_unix or platform_name == 'Cygwin'
    - name: Checks if platform's terminal exists (Windows)
      changed_when: false
      failed_when: find_mt_res.matched == 0
      ansible.windows.win_find:
        paths: '{{ mt_runner_mt_path_host }}'
        patterns: terminal*.exe
        recurse: true
      register: find_mt_res_win
      when: platform_name == 'Windows'
    - name: Consolidate terminal find result
      ansible.builtin.set_fact:
        find_mt_res: "{{ find_mt_res_win if platform_name == 'Windows' else find_mt_res_unix }}"
    - name: Store platform's path
      ansible.builtin.set_fact:
        find_mt_path: >-
          {{ '"' + find_mt_res.files[0].path + '"' if platform_name != 'Windows'
          else find_mt_res.files[0].path }}
        find_mt_path_folder: >-
          {{ find_mt_res.files[0].path | win_dirname if platform_name == 'Windows'
          else find_mt_res.files[0].path | dirname }}
      when: find_mt_res.files | length > 0
    - name: Checks if platform's editor exists (Unix/Cygwin)
      changed_when: false
      failed_when: find_mte_res.matched == 0
      ansible.builtin.find:
        paths: '{{ mt_runner_mt_path_host }}'
        patterns: '[mM]eta[eE]ditor*.exe'
        recurse: true
      register: find_mte_res_unix
      when: is_unix or platform_name == 'Cygwin'
    - name: Checks if platform's editor exists (Windows)
      changed_when: false
      failed_when: find_mte_res.matched == 0
      ansible.windows.win_find:
        paths: '{{ mt_runner_mt_path_host }}'
        patterns: '[mM]eta[eE]ditor*.exe'
        recurse: true
      register: find_mte_res_win
      when: platform_name == 'Windows'
    - name: Consolidate editor find result
      ansible.builtin.set_fact:
        find_mte_res: "{{ find_mte_res_win if platform_name == 'Windows' else find_mte_res_unix }}"
    - name: Store platform's editor path
      ansible.builtin.set_fact:
        find_mte_path: >-
          {{ '"' + find_mte_res.files[0].path + '"' if platform_name != 'Windows'
          else find_mte_res.files[0].path }}
        find_mte_path_folder: >-
          {{ find_mte_res.files[0].path | win_dirname if platform_name == 'Windows'
          else find_mte_res.files[0].path | dirname }}
      when: find_mte_res.files | length > 0
    - name: Check WSL's default distribution name (Windows)
      changed_when: false
      failed_when: not wsl_distribution_name_result
      ansible.windows.win_powershell:
        script: >
          wsl -l -v | Select-String -Pattern '\*'
          | ForEach-Object { ($_ -split '\s+')[1] }
      register: wsl_distribution_name_result
      when: platform_name == 'Windows'
    - name: Store WSL's default distribution name (Windows)
      ansible.builtin.set_fact:
        wsl_distribution_name: >-
          {{ wsl_distribution_name_result.output[0]
          | regex_replace("\u0000", "") }}
      when: platform_name == 'Windows'
    - name: Check WSL's default user name (Windows)
      changed_when: false
      failed_when: not wsl_user_name_result
      ansible.windows.win_command: ubuntu -c "whoami"
      register: wsl_user_name_result
      when: platform_name == 'Windows'
    - name: Store WSL's default user name (Windows)
      ansible.builtin.set_fact:
        wsl_user_name: '{{ wsl_user_name_result.stdout_lines[0] }}'
      when: platform_name == 'Windows'
