---
metatrader_become_method:
  Alpine: ansible.builtin.su
  Darwin: ansible.builtin.sudo
  Debian: ansible.builtin.su
  OtherLinux: ansible.builtin.su
  Ubuntu: ansible.builtin.su
  Windows: ansible.builtin.runas
