---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: windows
    image: mcr.microsoft.com/windows/servercore:ltsc2022
provisioner:
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible-tmp-$${USER}
  name: ansible
  inventory:
    group_vars:
      all:
        wine_install_winetricks: true
verifier:
  name: ansible
