---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: debian-latest
    image: debian:latest
  - name: nixos-latest
    dockerfile: ../resources/playbooks/Dockerfile.j2
    image: nixos/nix:latest
    pre_build_image: false
  - name: ubuntu-jammy
    image: ubuntu:jammy
  - name: ubuntu-noble
    image: ubuntu:noble
  - name: ubuntu-latest
    image: ubuntu:latest
provisioner:
  config_options:
    defaults:
      # Use the built-in default callback with result_format instead of community.general.yaml
      stdout_callback: ansible.builtin.default
      remote_tmp: /tmp/.ansible-tmp-$${USER}
  name: ansible
  inventory:
    group_vars:
      all:
        wine_install_winetricks: true
        wine_release: stable
        wine_winetricks_winver: win10
verifier:
  name: ansible
