---
- name: Converge
  hosts: all
  tasks:
    - name: Include main role
      ansible.builtin.import_role:
        name: ea31337.metatrader
      vars:
        metatrader_setup_url: |
          https://download.mql5.com/cdn/web/3315/mt4/xm4setup.exe
        metatrader_version: 4
        # noqa: var-naming[no-role-prefix]
        wine_winetricks_winver: win10
