---
- name: Verify
  hosts: all
  vars:
    effective_home: >-
      {{ ansible_facts.get('user_dir')
      | default(ansible_facts.get('env', {}).get('HOME'), true)
      | default('/root', true) }}
  tasks:
    - name: Retrieve information from path
      ansible.builtin.stat:
        path: '{{ effective_home }}/.wine/drive_c/Program Files'
      register: stat_result
    - name: Verify Program Files directory exist
      ansible.builtin.assert:
        that:
          - stat_result.stat.exists
          - stat_result.stat.isdir
    - name: Check if Meta Terminal exists
      changed_when: false
      failed_when: find_mt_res.matched == 0
      ansible.builtin.find:
        paths: '{{ effective_home }}/.wine/drive_c'
        patterns: terminal*.exe
        recurse: true
      register: find_mt_res
      when: ansible_facts.get('os_family', '') != "Windows"
    - name: Checks if platform's editor exists
      changed_when: false
      failed_when: find_mte_res.matched == 0
      ansible.builtin.find:
        paths: '{{ effective_home }}/.wine/drive_c'
        patterns: '[mM]eta[eE]ditor*.exe'
        recurse: true
      register: find_mte_res
      when: ansible_facts.get('os_family', '') != "Windows"
