---
name: Molecule

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - mt4
          - default
    steps:
      - uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2
        env:
          ANSIBLE_STDOUT_CALLBACK: debug
        with:
          molecule_args: --scenario-name ${{ matrix.scenario }}
          molecule_options: --verbose
          molecule_working_dir: "${{ github.repository }}"
    timeout-minutes: 30
