---
name: Platform

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - '.github/workflows/platform.yml'
  push:
    branches:
      - 'master'
      - '*dev*'
    paths:
      - '.github/workflows/platform.yml'
  workflow_call:

jobs:
  Install-MT4-Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installs platform
        uses: dawidd6/action-ansible-playbook@v2
        with:
          configuration: |
            [defaults]
            nocows = false
            stdout_callback = yaml
          directory: ${{ github.workspace }}
          options: |
            --connection local
            --inventory localhost,
            --verbose
          playbook: molecule/mt4/converge.yml
          requirements: meta/galaxy-requirements.yml
      - uses: actions/upload-artifact@v4
        with:
          name: platform4
          path: |
            ~/.wine/drive_c/Program Files*/**/*MT*
            ~/.wine/drive_c/Program Files*/**/*Meta*
    timeout-minutes: 20
  Install-MT5-Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installs platform
        uses: dawidd6/action-ansible-playbook@v2
        with:
          configuration: |
            [defaults]
            nocows = false
            stdout_callback = yaml
          directory: ${{ github.workspace }}
          options: |
            --connection local
            --inventory localhost,
            --verbose
          playbook: molecule/mt5/converge.yml
          requirements: meta/galaxy-requirements.yml
      - uses: actions/upload-artifact@v4
        with:
          name: platform5
          path: |
            ~/.wine/drive_c/Program Files*/**/*MT*
            ~/.wine/drive_c/Program Files*/**/*Meta*
    timeout-minutes: 20
  Cleanup-MT-Linux:
    needs:
      - Install-MT4-Linux
      - Install-MT5-Linux
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v4
        with:
          name: platform*
