---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: windows
    image: mcr.microsoft.com/windows/servercore:ltsc2022
provisioner:
  config_options:
    defaults:
      stdout_callback: ansible.builtin.default
      remote_tmp: /tmp/.ansible-tmp-$${USER}
  name: ansible
  inventory:
    group_vars:
      all:
        metatrader_version: 5
        wine_install_winetricks: true
  options:
    v: true
  playbooks:
    converge: ../default/converge.yml
    prepare: ../default/prepare.yml
verifier:
  name: ansible
